server.port=8888
# \u963F\u91CC\u767E\u70BC\u6A21\u578B\u914D\u7F6E
langchain4j.community.dashscope.chat-model.api-key=${DASHSCOPE_API_KEY:}
langchain4j.community.dashscope.chat-model.model-name=qwen3-max
langchain4j.community.dashscope.tokenizer.api-key=${DASHSCOPE_API_KEY:}
langchain4j.community.dashscope.tokenizer.model-name=qwen3-max
# embedding\u6A21\u578B
langchain4j.community.dashscope.embedding-model.api-key=${DASHSCOPE_API_KEY:}
langchain4j.community.dashscope.embedding-model.model-name=text-embedding-v4



# \u65E5\u5FD7\u7EA7\u522B
#logging.level.root=debug

#MongoDB\u914D\u7F6E
spring.data.mongodb.uri=${MONGODB_URI:mongodb://root:123456@localhost:27017/chat_memory_db?authSource=admin}

# =========================
# \u6570\u636E\u6E90\u57FA\u672C\u914D\u7F6E
# =========================
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3310/guiguxiaozhi?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:root123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# =========================
# Hikari \u8FDE\u63A5\u6C60\u53EF\u9009\u914D\u7F6E
# =========================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariCP

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=5000ms
# Redis embedding store
langchain4j.community.redis.host=${REDIS_HOST:localhost}
langchain4j.community.redis.port=${REDIS_PORT:6380}
langchain4j.community.redis.dimension=1024
langchain4j.community.redis.index-name=medibuddy_embedding_index
langchain4j.community.redis.prefix=medibuddy:
